## add this entry to your configuration.yaml
## lanrelay IP address in example - 192.168.5.24
## first channel shortly switch-return for push i5 computer turnon/off button
## second channel have two positions and turn on or off audio system connected to PC

# Relay SR-201
command_line:
  - switch:
        name: i5 Power
        scan_interval: 2
        command_on: echo -n 11:1 | nc 192.168.5.24 6722
#       command_off: echo -n 21:1 | nc 192.168.5.24 6722
        command_state: echo -n '00:0^' | nc 192.168.5.24 6722
        value_template: '{{ value[0:1] == "1" }}'
  - switch:
        name: i5 Speakers
        command_on: echo -n 12:0 | nc 192.168.5.24 6722
        command_off: echo -n 22:0 | nc 192.168.5.24 6722
        command_state: echo -n '00:0^' | nc 192.168.5.24 6722
        value_template: '{{ value[1:2] == "1" }}'
