name: "SR-201 LAN Relay"
description: "Home Assistant Addon for SR-201 LAN TCP Relay boards"
version: "1.2"
slug: "sr201"
url: "https://github.com/mamontuka/sr201-ha"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  relay_boards:
    - device_id: "sr201_1"
      enabled: true
      friendly_name: "SR-201 Board 1"
      relay_ip: "192.168.0.100"
      relay_port: 6722
      relay_count: 2
      inverted_relays: []
      triggers: []
    - device_id: "sr201_2"
      enabled: false
      friendly_name: "SR-201 Board 2"
      relay_ip: "192.168.0.101"
      relay_port: 6722
      relay_count: 2
      inverted_relays: []
      triggers: []
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "homeassistant"
  mqtt_password: "your_mqtt_password"
  relay_poll_interval: 2
schema:
  relay_boards:
    - device_id: str
      enabled: bool
      friendly_name: str
      relay_ip: str
      relay_port: int
      relay_count: int
      inverted_relays:
        - int
      triggers:
        - int
  mqtt_broker: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password
  relay_poll_interval: int
